# Generated by Django 4.2.3 on 2024-04-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.TextField(blank=True, default='https://www.gravatar.com/avatar/', max_length=500),
        ),
    ]
