# Generated by Django 4.2.3 on 2024-05-17 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_otp_user_otp_expiry_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_expiry_time',
        ),
    ]
