# Generated by Django 4.2.3 on 2024-05-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_otp_user_otp_expiry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invited',
            field=models.UUIDField(blank=True, default=0),
        ),
    ]
