version: "3"

services:
  frontend:
    container_name: frontend
    env_file: .env
    build: docker/nginx/
    ports:
      - 8000:8000
    volumes:
      - frontend-data:/var/www/html/
  
  backend:
    container_name: backend
    build: docker/backend/
    restart: on-failure
    command: python /usr/src/app/manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    volumes:
      - backend-data:/usr/src/app/
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - server
  db:
    container_name: db
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - server
    healthcheck:
        test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
        interval: 10s
        timeout: 5s
        retries: 5
  

volumes:
  frontend-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${DATA_FOLDER}/frontend"

  backend-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${DATA_FOLDER}/backend"

  db-data:
  pgadmin-data:

networks:
  server: