# Generated by Django 4.2.3 on 2024-05-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_match_alias1_match_alias2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='alias1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='alias2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player2',
        ),
        migrations.AddField(
            model_name='matchpoints',
            name='alias',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
